name: $(majorMinorVersion)$(Rev:.r)-CI

trigger:
  batch: true
  branches:
    include:
    - develop
    - master
    - release/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
  workingDirectory: 'src/carbon.app/ClientApp'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'src/carbon.app/ClientApp/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/carbon.app.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'carbon.app.zip'
    publishLocation: 'Container'
